title: Siyu Chen's Homepage
page-top-title: Siyu Chen
top-section-bg-text: Be what you wanna be
home-subtitle: Siyu Chen&ensp;|&ensp;陈思宇
copyright-text: '&copy; Siyu Chen 2023-2025. All Rights Reserved.'
